default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOSTNAME') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  timeout: 5000

development:
  <<: *default
  database: camaleon_cms_sample_development

test:
  <<: *default
  database: camaleon_cms_sample_test

production:
  <<: *default
  database: camaleon_cms_sample_production
